### ISSUE TITLE
the command line doesn't work

### ISSUE THREAD

**Issue by EndlessIdea** [trek-view/fusion2sphere#1]
Hi I clone this project and install it as the readme.md on my mac.
After installing, I try to execute it locally, 
`./fusion2sphere -f testframes/GF075169.JPG testframes/GB075169.JPG -o test.jpg parameter-examples/photo-mode.txt`
but it reports an error 
**Expected two fisheye images, only found 0
Failed to read parameter file "parameter-examples/photo-mode.txt"**

Could you help give some instructions?

**Comment by EndlessIdea** [comment]
@himynamesdave

**Comment by himynamesdave** [comment]
Hey @EndlessIdea , I forgot to add the IMAGE line to the lookup. Should work now with commit:

https://github.com/trek-view/fusion2sphere/commit/e87651acc9b2dd01ab4a361aa7f8481be93e3689

**Comment by EndlessIdea** [comment]
@himynamesdave  Many thanks!
