### ISSUE TITLE
Parameter examples

### ISSUE THREAD

**Issue by victormac3000** [trek-view/fusion2sphere#4]
I’ve the beta firmware (2.00) on my Fusion and I’ve recorded a video in 5,8k 24fps. 
¿How can I calculate the correct parameters for that resolution?
Thanks for making this awesome software

**Comment by himynamesdave** [comment]
Do these posts help @victormac3000?

https://www.trekview.org/blog/2022/using-ffmpeg-process-gopro-fusion-fisheye/
https://www.trekview.org/blog/2021/gopro-fusion-fisheye-stitching-part-1/
https://www.trekview.org/blog/2021/gopro-fusion-fisheye-stitching-part-2/
https://www.trekview.org/blog/2021/gopro-fusion-fisheye-stitching-part-3/
https://www.trekview.org/blog/2022/gopro-fusion-fisheye-stitching-part-4/

I have added these to the readme in the latest commit for others.

https://github.com/trek-view/fusion2sphere/commit/6568e0e02c89a40f89ed76511006c6fd96ddba3f

As such, will close for now.
