### ISSUE TITLE
Samsung Gear360 support version

### ISSUE THREAD

**Issue by joeyvanderbie** [trek-view/fusion2sphere#5]
Hi, thanks for creating this great code!

I managed to use this for images of the Samsung Gear360 (2017 edition) by only adjusting the settings file. (currently only support photos)
I created a cloned repo at https://github.com/joeyvanderbie/samsunggear3602sphere
I did not renamed and reworked al the files, so it is in current format a dirty clone. 
But I still wanted to share it, hoping somebody else might find it useful.

Might I suggest that for future versions I would propose to merge the GoPro Fusion, Max, and now Samsung Gear360 versions into 1 version, where the user can select the correct camera and settings using flags.

**Comment by himynamesdave** [comment]
Hey @joeyvanderbie ! Nice work. For now I will keep this project focused on the Fusion, only because I know GoPro best.

I'll add a link to your Gear 360 alternative though.
